force-app/main/default/objects/Product_Catalog__c/Product_Catalog__c.object-meta.xml
<CustomObject>
    <label>Product Catalog</label>
    <nameField>
        <displayFormat>MM-{0000}</displayFormat>
        <label>Product Catalog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Notification__c/Product_Notification__c.object-meta.xml
<CustomObject>
    <label>Product Notification</label>
    <nameField>
        <displayFormat>M69-{0000}</displayFormat>
        <label>Product Notification  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Notification__c/fields/Product_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Product_Catalog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Catalog</label>
    <referenceTo>Product_Catalog__c</referenceTo>
    <relationshipLabel>Product Notifications</relationshipLabel>
    <relationshipName>Product_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Notification__c/fields/Subscribe__c.field-meta.xml
<CustomField>
    <fullName>Subscribe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscribe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProductSubject.cls
public with sharing class ProductSubject implements ISubject{
    String id;

    public ProductSubject(String id){
        this.id = id;
    }

    public void subscribe(Product_Notification__c observer){
        System.debug('called subscribe');
        //// this is where the Subject Class (this one) is calling its one to many observers
        observer.Product_Catalog__c = this.id;
        observer.Subscribe__c = true;
        if (Schema.sObjectType.Product_Notification__c.isCreateable()) {
            insert observer;
        }
    }

    public void unsubscribe(Product_Notification__c observer){

        System.debug('called unsubscribe');
        // observer.Product_Catalog__c = this.id;
        // observer.Subscribe__c = false;
        // if (Schema.sObjectType.Product_Notification__c.isCreateable()) {
        //     insert observer;
        // }
    }

    public void notifyObserver(){

        System.debug('Notify Calling');
        IObserver observer = new ProductObserver(this.id);
        observer.notifity();
    }
}