force-app/main/default/objects/Product_Catalog__c/Product_Catalog__c.object-meta.xml
<CustomObject>
    <label>Product Catalog</label>
    <nameField>
        <displayFormat>MM-{0000}</displayFormat>
        <label>Product Catalog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Notification__c/Product_Notification__c.object-meta.xml
<CustomObject>
    <label>Product Notification</label>
    <nameField>
        <displayFormat>M69-{0000}</displayFormat>
        <label>Product Notification  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Notification__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Product_Notification__c/fields/Product_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Product_Catalog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Catalog</label>
    <referenceTo>Product_Catalog__c</referenceTo>
    <relationshipLabel>Product Notifications</relationshipLabel>
    <relationshipName>Product_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Notification__c/fields/Subscribe__c.field-meta.xml
<CustomField>
    <fullName>Subscribe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Subscribe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProductObserver.cls
public with sharing class ProductObserver implements IObserver {
    String id;
    public ProductObserver(String id) {
        this.id = id;
    }


    public void notifity(){
        System.debug('notify from the ProductObserver');

        ///// try to avoid inline queries like this, can use the builder pattern to escape this
        List<Product_Notification__c> observers = [
            SELECT Id, Email_Address__c
            FROM Product_Notification__c
            WHERE Product_Catalog__c = :this.id
            AND Subscribe__c = TRUE
            WITH SECURITY_ENFORCED
        ];

        for (Product_Notification__c observer : observers) {
            System.debug('pretend this is sending an email to : ' + observer.Email_Address__c);
        }
    }

}