force-app/main/default/objects/Test_Platty_Event__e/Test_Platty_Event__e.object-meta.xml
<CustomObject>
    <label>Test Platty Event</label>
    <pluralLabel>Test Platty Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Test_Platty_Event__e/fields/Little_Message__c.field-meta.xml
<CustomField>
    <fullName>Little_Message__c</fullName>
    <description>A nice little test message</description>
    <label>Little Message</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FirePlatformEvent.cls
/*
*********************************************************
Apex Class Name    : FirePlatformEvent
Created Date       : 12/20/23
@description       : Class to create a Platform Event from a LWC
@author            : Mike Meadows |  mmeadow33@gmail.com
Modification Log:
Ver   Date         Author                               Modification
1.0   12/20/23   Mike Meadows                           Initial Version
1.1   12/21/23   Mike Meadows                           Created a Commment Framework
*********************************************************
*/
public with sharing class FirePlatformEvent {
       /* *********************************************************
        @Method Name    : fireEvent
        @author         : Mike Meadows
        @description    : only method, used to fire Platform Event
        @param          : {String} message
        @return         : void
    ********************************************************
    */ 
    @AuraEnabled
    public static void fireEvent(String message){
        Test_Platty_Event__e event = new Test_Platty_Event__e();
        event.Little_Message__c = message;
        EventBus.publish(event);
    }
}