force-app/main/default/objects/Discounts__mdt/Discounts__mdt.object-meta.xml
<CustomObject>
    <description>For Factory Pattern</description>
    <label>Discounts</label>
    <pluralLabel>Discounts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Discounts__mdt/fields/Class_To_Instantiate__c.field-meta.xml
<CustomField>
    <fullName>Class_To_Instantiate__c</fullName>
    <description>For Factory Pattern</description>
    <label>Class To Instantiate</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discounts__mdt/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <description
  >For Factory Pattern, we would probably want this as a picklist</description>
    <label>Customer Tier</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discounts__mdt/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description
  >For Factory Pattern, this prevents hardcoding the number in Apex</description>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DiscountFactory.cls
public with sharing class DiscountFactory {

    public static IDiscount getDiscount(string customerTier){
        Discounts__mdt discountMeta = [Select Class_To_Instantiate__c, Discount__c From Discounts__mdt Where Customer_Tier__c = :customerTier WITH SECURITY_ENFORCED];
        //// Type class allows us to instantiate a class by its name
        Type t = Type.forName(discountMeta.Class_To_Instantiate__c); //// so calling the Class from the metadata field 
        IDiscount discount = (IDiscount)t.newInstance();  /// instantiate the Type t class, has to be Type-cast
        return discount;
    }
}