force-app/main/default/objects/Discounts__mdt/Discounts__mdt.object-meta.xml
<CustomObject>
    <description>For Factory Pattern</description>
    <label>Discounts</label>
    <pluralLabel>Discounts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Discounts__mdt/fields/Customer_Tier__c.field-meta.xml
<CustomField>
    <fullName>Customer_Tier__c</fullName>
    <description
  >For Factory Pattern, we would probably want this as a picklist</description>
    <label>Customer Tier</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discounts__mdt/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description
  >For Factory Pattern, this prevents hardcoding the number in Apex</description>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GoldDiscount.cls
public with sharing class GoldDiscount implements IDiscount{
    private Decimal discount;
    
    public GoldDiscount(){
        this.discount = [Select Discount__c From Discounts__mdt Where Customer_Tier__c = 'Gold' WITH SECURITY_ENFORCED].Discount__c;
        System.debug(this.discount);
    }

    public Decimal calculateDiscount(Decimal oppAmount) {
        System.debug( this.discount);
        return oppAmount - (oppAmount * this.discount);
    }

}